=== Battlecruiser/L2J_DataPack/L2J_DataPack/dist/game/data/xsd/armorSets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="set" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="bonus_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skill" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="set" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="bonus_skill" minOccurs="0" maxOccurs="unbounded" >
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="enchant_skill" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="enchantLevel" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required" type="xs:positiveInteger" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Battlecruiser/L2J_DataPack/L2J_DataPack/dist/game/data/stats/armorsets/s84_vorpal_pvp.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/armorSets.xsd">
	<!-- S84 Vorpal PVP Armor Sets -->
	<set id="194">
		<item id="16171" /> <!-- Vorpal Breastplate {PvP} -->
		<item id="15595" /> <!-- Vorpal Gaiter -->
		<item id="15589" /> <!-- Vorpal Helmet -->
		<item id="15598" /> <!-- Vorpal Gauntlet -->
		<item id="15601" /> <!-- Vorpal Boots -->
		<bonus_item id="15604" /> <!-- Vorpal Shield -->
		<skill set="5" id="3006" level="1" /> <!-- Equip Set Items -->
		<skill set="5" id="8409" level="1" /> <!-- Vorpal Heavy Armor Set - PVP -->
		<bonus_skill id="8495" level="1" /> <!-- Vorpal Shield -->
		<enchant_skill enchantLevel="6" id="8461" level="1" /> <!-- Enchant Heavy Armor (S Grade) -->
	</set>
	<set id="195">
		<item id="16172" /> <!-- Vorpal Leather Breastplate {PvP} -->
		<item id="15596" /> <!-- Vorpal Leather Legging -->
		<item id="15590" /> <!-- Vorpal Leather Helmet -->
		<item id="15599" /> <!-- Vorpal Leather Gloves -->
		<item id="15602" /> <!-- Vorpal Leather Boots -->
		<skill set="5" id="3006" level="1" /> <!-- Equip Set Items -->
		<skill set="5" id="8410" level="1" /> <!-- Vorpal Leather Armor Set - PVP -->
		<enchant_skill enchantLevel="6" id="8462" level="1" /> <!-- Enchant Light Armor (S Grade) -->
	</set>
	<set id="196">
		<item id="16173" /> <!-- Vorpal Tunic {PvP} -->
		<item id="15597" /> <!-- Vorpal Stockings -->
		<item id="15591" /> <!-- Vorpal Circlet -->
		<item id="15600" /> <!-- Vorpal Gloves -->
		<item id="15603" /> <!-- Vorpal Shoes -->
		<skill set="5" id="3006" level="1" /> <!-- Equip Set Items -->
		<skill set="5" id="8411" level="1" /> <!-- Vorpal Robe Set - PVP -->
		<enchant_skill enchantLevel="6" id="8463" level="1" /> <!-- Enchant Robe (S Grade) -->
	</set>
</list>
